'use strict';
// Generates engine/pmath-table.js: a FROZEN sine lookup table for the portable-math epoch (pmath-1).
//
// WHY frozen data (not computed at load): if the table were built at runtime with Math.sin, we'd be right back
// to depending on the host engine's trig -- the exact non-portability we're removing. So we compute it ONCE
// here (with Math.sin) and commit the resulting DECIMAL LITERALS. At runtime the engine only ever parses those
// literals (ECMAScript mandates correctly-rounded decimal->double, identical on every engine/CPU) and does
// + - * / floor -- all bit-identical everywhere. See docs/PLAN-engine-portable-math.md.
//
// Regenerating this file is a DELIBERATE EPOCH BUMP (every run's bytes change) -- it needs its own review, like
// the JJ oracle regenerators. The committed sha256 in test/engine/pmath.test.js guards against accidental drift.
//
//   node tools/pmath/gen-table.mjs [N]     (N = table size, power of two; default 1024)

import { writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const N = Number(process.argv[2] || 1024);
if (!Number.isInteger(Math.log2(N))) { console.error('N must be a power of two'); process.exit(2); }

const TWO_PI = Math.PI * 2;
// N+1 entries: the guard entry T[N] == T[0] lets linear interp read T[idx+1] without a wrap branch.
const vals = [];
for (let i = 0; i <= N; i++) {
  const v = Math.sin((i / N) * TWO_PI);
  // shortest round-trip literal; verify it parses back EXACTLY (the one way decimal storage could bite).
  const lit = v.toString();
  if (Number(lit) !== v) { console.error(`entry ${i} does not round-trip: ${lit}`); process.exit(1); }
  vals.push(lit);
}

const body = vals.join(',');
const out = `'use strict';
// AUTO-GENERATED by tools/pmath/gen-table.mjs -- DO NOT EDIT BY HAND.
// Frozen sine table for the portable-math epoch. Regenerating is a deliberate epoch bump (see the generator).
// ${N} intervals over [0, 2*PI); index N is a guard equal to index 0.
export const SIN_N = ${N};
export const SIN_TABLE = Float64Array.of(${body});
`;

const here = dirname(fileURLToPath(import.meta.url));
const dest = join(here, '..', '..', 'engine', 'pmath-table.js');
writeFileSync(dest, out);

// sha256 over the canonical value sequence (not the file text) -- stable across formatting tweaks.
const hash = createHash('sha256').update(vals.join(',')).digest('hex');
console.log(`wrote ${dest}`);
console.log(`SIN_N=${N}  entries=${vals.length}  sha256(values)=${hash}`);
