// GenePool desktop (Electron) MAIN process. One app, one process tree: a Chromium renderer runs the existing
// micrograph viewer (WebGL + the JS engine), and this Node 24 main process gives it REAL files + SQLite recording
// via IPC -- reusing the tested tools/events pipeline verbatim (node:sqlite). No personal browser, no separate server
// (the loopback below is internal to the app, only so the renderer's ES modules + font load exactly as in dev).
import { app, BrowserWindow, ipcMain, dialog, utilityProcess } from 'electron';
import { createServer } from 'node:http';
import { readFile, writeFile } from 'node:fs/promises';
import { existsSync, mkdirSync } from 'node:fs';
import { extname, join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createSqliteSink } from '../tools/events/sqlite-sink.mjs';
import { createJsonlSink } from '../tools/events/jsonl-sink.mjs';
import { openRunReader } from '../tools/events/run-db.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');                 // repo root: serves the viewer + engine + fonts to our own renderer
const MIME = { '.html':'text/html', '.js':'text/javascript', '.mjs':'text/javascript', '.json':'application/json',
  '.ttf':'font/ttf', '.css':'text/css', '.png':'image/png', '.wasm':'application/wasm' };

// --- internal loopback static server (127.0.0.1, ephemeral port) -> ES modules/fetch work as in the browser ---
function startStaticServer(){
  return new Promise((res, rej) => {
    const srv = createServer(async (req, q) => {
      try {
        let p = decodeURIComponent((req.url || '/').split('?')[0]); if (p === '/') p = '/viewer-micrograph-gl.html';
        const fp = join(ROOT, p);
        if (!fp.startsWith(ROOT) || !existsSync(fp)) { q.writeHead(404); q.end('not found'); return; }
        q.writeHead(200, { 'Content-Type': MIME[extname(fp)] || 'application/octet-stream' });
        q.end(await readFile(fp));
      } catch (e) { q.writeHead(500); q.end(String(e)); }
    });
    srv.on('error', rej);
    srv.listen(0, '127.0.0.1', () => res(srv.address().port));
  });
}

// --- recording: one .db holds the whole run (initial + periodic World.serialize() snapshots, plus the event stream);
//     a sibling .jsonl is the append-only source of truth. Both are pure observers of the engine's onEvent stream. ---
let rec = null;   // { sqlite, jsonl, snapStmt, path, events }
function recordStart({ base, seed, config, snapshot }){
  const dbPath = base.replace(/\.(db|jsonl|json)$/i, '') + '.db';
  const jsonlPath = dbPath.replace(/\.db$/, '.jsonl');
  const sqlite = createSqliteSink(dbPath);
  sqlite.db.exec('CREATE TABLE IF NOT EXISTS snapshots (tick INTEGER, json TEXT)');   // full checkpoints for instant resume
  const snapStmt = sqlite.db.prepare('INSERT INTO snapshots (tick, json) VALUES (?, ?)');
  sqlite.db.exec('CREATE TABLE IF NOT EXISTS run_meta (k TEXT PRIMARY KEY, v TEXT)');
  sqlite.db.prepare('INSERT OR REPLACE INTO run_meta (k,v) VALUES (?,?)').run('config', JSON.stringify({ seed, config }));
  const jsonl = createJsonlSink(jsonlPath, { runId: null, seed, config });
  if (snapshot){ snapStmt.run(snapshot.clock ?? 0, JSON.stringify(snapshot)); jsonl.onEvent({ type: 'snapshot', tick: snapshot.clock ?? 0, snapshot }); }
  rec = { sqlite, jsonl, snapStmt, path: dbPath, events: 0 };
  return dbPath;
}
function recordEvents(events){
  if (!rec) return;
  for (const e of events){ rec.sqlite.onEvent(e); rec.jsonl.onEvent(e); rec.events++; }
}
function recordSnapshot(snapshot){ if (rec && snapshot){ rec.snapStmt.run(snapshot.clock ?? 0, JSON.stringify(snapshot)); rec.jsonl.onEvent({ type:'snapshot', tick: snapshot.clock ?? 0, snapshot }); } }
function recordStop(){ if (!rec) return null; const { path, events } = rec; rec.jsonl.close(); rec.sqlite.close(); rec = null; return { path, events }; }

// --- scrub/playback: a per-seed run is generated by a utilityProcess (real Node, same V8 as the renderer -> D1) and
//     read back here via a read-only WAL reader, so the renderer can scrub a run WHILE it is still being generated. ---
let scrub = null;   // { seed, child, reader, dbPath, ready }
function runsDir(){ const d = join(app.getPath('userData'), 'runs'); mkdirSync(d, { recursive: true }); return d; }
function stopGenerator(){
  if (!scrub) return;
  try { scrub.reader?.close(); } catch { /* already closed */ }
  try { scrub.child?.kill(); } catch { /* already gone */ }
  scrub = null;
}
// Select (or start generating) a seed's run. Resolves once the .db is readable (the S3 "db ready" handshake).
function selectSeed(seed){
  return new Promise((resolve) => {
    if (scrub && scrub.seed === seed && scrub.ready){
      resolve({ ok: true, seed, frontier: scrub.reader.frontier(), runConfig: scrub.reader.runConfig() });
      return;
    }
    stopGenerator();                                            // kill+respawn on seed change (S5)
    const dbPath = join(runsDir(), `run-${seed}.db`);
    const resume = existsSync(dbPath);                          // continue a partial run (S4)
    const child = utilityProcess.fork(join(HERE, 'generator.mjs'));
    const s = { seed, child, reader: null, dbPath, ready: false };
    scrub = s;
    child.on('message', (m) => {
      if (s !== scrub) return;                                  // a newer seed superseded this child
      if (m.type === 'ready'){
        try { s.reader = openRunReader(dbPath); s.ready = true;
          resolve({ ok: true, seed, frontier: s.reader.frontier(), runConfig: s.reader.runConfig() }); }
        catch (e){ resolve({ ok: false, error: String(e) }); }
      } else if (m.type === 'progress'){
        if (win && !win.isDestroyed()) win.webContents.send('scrub:frontier', { seed: s.seed, tick: m.tick });   // tag with the seed so the renderer drops a killed run's late frontier
      } else if (m.type === 'done'){
        if (win && !win.isDestroyed()) win.webContents.send('scrub:done', m);
      } else if (m.type === 'error' && !s.ready){ resolve({ ok: false, error: m.message }); }
    });
    child.on('exit', () => { if (s === scrub && !s.ready) resolve({ ok: false, error: 'generator exited before ready' }); });
    // UNBOUNDED generation (Karl): the utilityProcess runs one core flat-out until it's killed (seed change / quit).
    // Safe because the run records ONLY keyframes, thinned to a fixed budget -> the file stays bounded (~230 MB) forever.
    child.postMessage({ seed, out: dbPath, opts: { resume, ticks: Infinity } });
  });
}
ipcMain.handle('scrub:select',    (_e, seed)  => selectSeed((seed >>> 0)));
ipcMain.handle('scrub:frontier',  ()          => scrub?.reader ? scrub.reader.frontier() : -1);
ipcMain.handle('scrub:keyframe',  (_e, t)     => scrub?.reader ? scrub.reader.getKeyframe(t) : null);
ipcMain.handle('scrub:stats',     (_e, t)     => scrub?.reader ? scrub.reader.getStats(t) : null);
ipcMain.handle('scrub:popSeries', (_e, opts)  => scrub?.reader ? scrub.reader.getPopSeries(opts || {}) : []);

let win = null;
async function createWindow(){
  const port = await startStaticServer();
  win = new BrowserWindow({
    width: 1120, height: 830, backgroundColor: '#0b0e13', title: 'GenePool',
    webPreferences: { preload: join(HERE, 'preload.cjs'), contextIsolation: true, sandbox: true },
  });
  // surface renderer warnings/errors + a crash to the main stdout (dev diagnostics for the scrub/playback UI)
  win.webContents.on('console-message', (_e, level, message, line, source) => {
    if (message && (message.includes('[fps]') || message.includes('[bench]'))) console.log(message);   // forward fps/bench readouts (real-GPU)
    else if (level >= 2) console.error(`[renderer] ${message}  (${source}:${line})`);
  });
  win.webContents.on('render-process-gone', (_e, d) => console.error('[renderer gone]', d.reason));
  const params = new URLSearchParams();                   // dev knob: GP_BENCH=1 -> real-GPU zoom-sweep bench (forwarded [bench] log)
  if (process.env.GP_BENCH) params.set('zoombench', '1');
  const q = params.toString() ? '?' + params.toString() : '';
  win.loadURL(`http://127.0.0.1:${port}/viewer-micrograph-gl.html${q}`);
}

// --- IPC: real files + recording, all in-process ---
ipcMain.handle('pool:save', async (_e, obj) => {
  const r = await dialog.showSaveDialog(win, { title: 'Save pool', defaultPath: 'pool.gpool.json',
    filters: [{ name: 'GenePool pool', extensions: ['json'] }] });
  if (r.canceled || !r.filePath) return { ok: false };
  await writeFile(r.filePath, JSON.stringify(obj));
  return { ok: true, path: r.filePath };
});
ipcMain.handle('pool:load', async () => {
  const r = await dialog.showOpenDialog(win, { title: 'Load pool', properties: ['openFile'],
    filters: [{ name: 'GenePool pool', extensions: ['json'] }] });
  if (r.canceled || !r.filePaths?.[0]) return { ok: false };
  return { ok: true, data: JSON.parse(await readFile(r.filePaths[0], 'utf8')), path: r.filePaths[0] };
});
// K-panel visual constants -> a real file in userData (survives relaunch; localStorage does NOT, since the window's
// loopback origin has an ephemeral port that changes each launch).
const paramsPath = () => join(app.getPath('userData'), 'micrograph-params.json');
ipcMain.handle('params:save', async (_e, obj) => {
  try { await writeFile(paramsPath(), JSON.stringify(obj, null, 2)); return { ok: true, path: paramsPath() }; }
  catch (e) { return { ok: false, error: String(e) }; }
});
ipcMain.handle('params:load', async () => {
  try { return JSON.parse(await readFile(paramsPath(), 'utf8')); } catch { return null; }
});
// Save a recorded viewer video (WebM bytes from the renderer's MediaRecorder) to a date/time-named file in ~/Movies/GenePool.
ipcMain.handle('video:save', async (_e, bytes) => {
  try {
    const dir = join(app.getPath('videos'), 'GenePool'); mkdirSync(dir, { recursive: true });
    const ts = new Date().toISOString().replace('T', '_').replace(/:/g, '-').replace(/\..+$/, '');   // 2026-09-07_15-30-12
    const path = join(dir, `genepool-${ts}.webm`);
    await writeFile(path, Buffer.from(bytes));
    return { ok: true, path };
  } catch (e) { return { ok: false, error: String(e) }; }
});
ipcMain.handle('pool:recordStart', async (_e, { seed, config, snapshot }) => {
  const r = await dialog.showSaveDialog(win, { title: 'Record run to SQLite', defaultPath: 'run.db',
    filters: [{ name: 'SQLite', extensions: ['db'] }] });
  if (r.canceled || !r.filePath) return { ok: false };
  const path = recordStart({ base: r.filePath, seed, config, snapshot });
  return { ok: true, path };
});
ipcMain.on('pool:record', (_e, events) => recordEvents(events));
ipcMain.handle('pool:recordSnapshot', (_e, snapshot) => { recordSnapshot(snapshot); return { ok: true }; });
ipcMain.handle('pool:recordStop', () => ({ ok: true, ...(recordStop() || {}) }));

app.whenReady().then(createWindow);
app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) createWindow(); });
app.on('before-quit', () => { stopGenerator(); });
app.on('window-all-closed', () => { recordStop(); stopGenerator(); app.quit(); });
